if (!window.gameQuestions) window.gameQuestions = {};

window.gameQuestions["اعلام"] = {
    // =============================================
    // 200 نقطة - سهل (أعلام مشهورة جداً)
    // =============================================
    "200": [
        { "question": "🇺🇸", "answer": "الولايات المتحدة الأمريكية" },
        { "question": "🇬🇧", "answer": "المملكة المتحدة" },
        { "question": "🇫🇷", "answer": "فرنسا" },
        { "question": "🇩🇪", "answer": "ألمانيا" },
        { "question": "🇨🇳", "answer": "الصين" },
        { "question": "🇯🇵", "answer": "اليابان" },
        { "question": "🇷🇺", "answer": "روسيا" },
        { "question": "🇮🇹", "answer": "إيطاليا" },
        { "question": "🇧🇷", "answer": "البرازيل" },
        { "question": "🇲🇽", "answer": "المكسيك" },
        { "question": "🇪🇬", "answer": "مصر" },
        { "question": "🇸🇦", "answer": "المملكة العربية السعودية" },
        { "question": "🇦🇪", "answer": "الإمارات العربية المتحدة" },
        { "question": "🇹🇷", "answer": "تركيا" },
        { "question": "🇮🇳", "answer": "الهند" },
        { "question": "🇰🇷", "answer": "كوريا الجنوبية" },
        { "question": "🇦🇺", "answer": "أستراليا" },
        { "question": "🇨🇦", "answer": "كندا" },
        { "question": "🇿🇦", "answer": "جنوب أفريقيا" },
        { "question": "🇦🇷", "answer": "الأرجنتين" },
        { "question": "🇵🇸", "answer": "فلسطين" },
        { "question": "🇲🇦", "answer": "المغرب" },
        { "question": "🇩🇿", "answer": "الجزائر" },
        { "question": "🇹🇳", "answer": "تونس" },
        { "question": "🇱🇾", "answer": "ليبيا" },
        { "question": "🇸🇩", "answer": "السودان" },
        { "question": "🇮🇶", "answer": "العراق" },
        { "question": "🇸🇾", "answer": "سوريا" },
        { "question": "🇯🇴", "answer": "الأردن" },
        { "question": "🇱🇧", "answer": "لبنان" },
        { "question": "🇰🇼", "answer": "الكويت" },
        { "question": "🇶🇦", "answer": "قطر" },
        { "question": "🇧🇭", "answer": "البحرين" },
        { "question": "🇴🇲", "answer": "عُمان" },
        { "question": "🇾🇪", "answer": "اليمن" },
        { "question": "🇮🇷", "answer": "إيران" },
        { "question": "🇵🇰", "answer": "باكستان" },
        { "question": "🇪🇸", "answer": "إسبانيا" },
        { "question": "🇵🇹", "answer": "البرتغال" },
        { "question": "🇳🇱", "answer": "هولندا" },
        { "question": "🇧🇪", "answer": "بلجيكا" },
        { "question": "🇨🇭", "answer": "سويسرا" },
        { "question": "🇦🇹", "answer": "النمسا" },
        { "question": "🇸🇪", "answer": "السويد" },
        { "question": "🇳🇴", "answer": "النرويج" },
        { "question": "🇩🇰", "answer": "الدنمارك" },
        { "question": "🇫🇮", "answer": "فنلندا" },
        { "question": "🇵🇱", "answer": "بولندا" },
        { "question": "🇬🇷", "answer": "اليونان" },
        { "question": "🇺🇦", "answer": "أوكرانيا" },
        { "question": "🇳🇬", "answer": "نيجيريا" },
        { "question": "🇰🇪", "answer": "كينيا" },
        { "question": "🇪🇹", "answer": "إثيوبيا" },
        { "question": "🇬🇭", "answer": "غانا" },
        { "question": "🇨🇴", "answer": "كولومبيا" },
        { "question": "🇻🇪", "answer": "فنزويلا" },
        { "question": "🇨🇱", "answer": "تشيلي" },
        { "question": "🇵🇪", "answer": "بيرو" },
        { "question": "🇮🇩", "answer": "إندونيسيا" },
        { "question": "🇲🇾", "answer": "ماليزيا" },
        { "question": "🇵🇭", "answer": "الفلبين" },
        { "question": "🇹🇭", "answer": "تايلاند" },
        { "question": "🇻🇳", "answer": "فيتنام" },
        { "question": "🇧🇩", "answer": "بنغلاديش" },
        { "question": "🇱🇰", "answer": "سريلانكا" },
        { "question": "🇳🇵", "answer": "نيبال" },
        { "question": "🇦🇫", "answer": "أفغانستان" },
        { "question": "🇮🇱", "answer": "إسرائيل" },
        { "question": "🇳🇿", "answer": "نيوزيلندا" },
        { "question": "🇸🇬", "answer": "سنغافورة" },
        { "question": "🇲🇲", "answer": "ميانمار" },
        { "question": "🇨🇿", "answer": "التشيك" },
        { "question": "🇷🇴", "answer": "رومانيا" },
        { "question": "🇭🇺", "answer": "المجر" },
        { "question": "🇸🇰", "answer": "سلوفاكيا" },
        { "question": "🇭🇷", "answer": "كرواتيا" },
        { "question": "🇷🇸", "answer": "صربيا" },
        { "question": "🇵🇭", "answer": "الفلبين" },
        { "question": "🇪🇨", "answer": "الإكوادور" },
        { "question": "🇧🇴", "answer": "بوليفيا" },
        { "question": "🇵🇾", "answer": "باراغواي" },
        { "question": "🇺🇾", "answer": "الأوروغواي" },
        { "question": "🇨🇷", "answer": "كوستاريكا" },
        { "question": "🇨🇺", "answer": "كوبا" },
        { "question": "🇺🇿", "answer": "أوزباكستان" },
        { "question": "🇲🇳", "answer": "منغوليا" },
        { "question": "🇭🇰", "answer": "هونج كونج" },
        { "question": "🇹🇼", "answer": "تايوان" },
        { "question": "🇵🇷", "answer": "بورتو ريكو" },
        { "question": "🇮🇪", "answer": "أيرلندا" },
        { "question": "🇮🇸", "answer": "آيسلندا" },
        { "question": "🇱🇺", "answer": "لوكسمبورغ" },
        { "question": "🇲🇹", "answer": "مالطا" },
        { "question": "🇲🇩", "answer": "مولدوفا" },
        { "question": "🇦🇲", "answer": "أرمينيا" },
        { "question": "🇬🇪", "answer": "جورجيا" },
        { "question": "🇦🇿", "answer": "أذربيجان" },
        { "question": "🇧🇾", "answer": "بيلاروسيا" },
        { "question": "🇱🇻", "answer": "لاتفيا" },
        { "question": "🇱🇹", "answer": "ليتوانيا" },
        { "question": "🇪🇪", "answer": "إستونيا" },
        { "question": "🇸🇴", "answer": "الصومال" },
        { "question": "🇹🇿", "answer": "تنزانيا" },
        { "question": "🇺🇬", "answer": "أوغندا" },
        { "question": "🇿🇲", "answer": "زامبيا" },
        { "question": "🇿🇼", "answer": "زيمبابوي" },
        { "question": "🇦🇴", "answer": "أنغولا" },
        { "question": "🇨🇩", "answer": "الكونغو الديمقراطية" },
        { "question": "🇨🇲", "answer": "الكاميرون" },
        { "question": "🇸🇳", "answer": "السنغال" },
        { "question": "🇨🇮", "answer": "ساحل العاج" },
        { "question": "🇲🇿", "answer": "موزمبيق" },
        { "question": "🇲🇬", "answer": "مدغشقر" },
        { "question": "🇮🇶", "answer": "العراق" },
        { "question": "🇵🇦", "answer": "بنما" },
        { "question": "🇳🇮", "answer": "نيكاراغوا" },
        { "question": "🇸🇻", "answer": "السلفادور" },
        { "question": "🇬🇹", "answer": "غواتيمالا" },
        { "question": "🇭🇳", "answer": "هندوراس" },
        { "question": "🇩🇴", "answer": "جمهورية الدومينيكان" },
        { "question": "🇯🇲", "answer": "جامايكا" },
        { "question": "🇭🇹", "answer": "هايتي" },
        { "question": "🇹🇹", "answer": "ترينيداد وتوباغو" },
        { "question": "🇧🇧", "answer": "باربادوس" },
        { "question": "🇰🇿", "answer": "كازاخستان" },
        { "question": "🇹🇲", "answer": "تركمانستان" },
        { "question": "🇹🇯", "answer": "طاجيكستان" },
        { "question": "🇰🇬", "answer": "قيرغيزستان" },
        { "question": "🇱🇦", "answer": "لاوس" },
        { "question": "🇰🇭", "answer": "كمبوديا" },
        { "question": "🇧🇳", "answer": "بروناي" },
        { "question": "🇫🇯", "answer": "فيجي" },
        { "question": "🇵🇬", "answer": "بابوا غينيا الجديدة" },
        { "question": "🇸🇸", "answer": "جنوب السودان" },
        { "question": "🇸🇱", "answer": "سيراليون" },
        { "question": "🇬🇳", "answer": "غينيا" },
        { "question": "🇧🇫", "answer": "بوركينا فاسو" },
        { "question": "🇲🇱", "answer": "مالي" },
        { "question": "🇳🇪", "answer": "النيجر" },
        { "question": "🇹🇩", "answer": "تشاد" }
    ],

    // =============================================
    // 400 نقطة - متوسط (أعلام متوسطة الشهرة)
    // =============================================
    "400": [
        { "question": "🇸🇮", "answer": "سلوفينيا" },
        { "question": "🇧🇦", "answer": "البوسنة والهرسك" },
        { "question": "🇽🇰", "answer": "كوسوفو" },
        { "question": "🇲🇰", "answer": "مقدونيا الشمالية" },
        { "question": "🇦🇱", "answer": "ألبانيا" },
        { "question": "🇲🇪", "answer": "الجبل الأسود" },
        { "question": "🇧🇬", "answer": "بلغاريا" },
        { "question": "🇸🇲", "answer": "سان مارينو" },
        { "question": "🇷🇼", "answer": "رواندا" },
        { "question": "🇧🇮", "answer": "بوروندي" },
        { "question": "🇩🇯", "answer": "جيبوتي" },
        { "question": "🇪🇷", "answer": "إريتريا" },
        { "question": "🇬🇶", "answer": "غينيا الاستوائية" },
        { "question": "🇬🇦", "answer": "الغابون" },
        { "question": "🇨🇬", "answer": "الكونغو" },
        { "question": "🇨🇫", "answer": "جمهورية أفريقيا الوسطى" },
        { "question": "🇧🇯", "answer": "بنين" },
        { "question": "🇹🇬", "answer": "توغو" },
        { "question": "🇬🇼", "answer": "غينيا بيساو" },
        { "question": "🇬🇲", "answer": "غامبيا" },
        { "question": "🇨🇻", "answer": "الرأس الأخضر" },
        { "question": "🇸🇨", "answer": "سيشيل" },
        { "question": "🇲🇺", "answer": "موريشيوس" },
        { "question": "🇰🇲", "answer": "جزر القمر" },
        { "question": "🇸🇹", "answer": "ساو تومي وبرينسيبي" },
        { "question": "🇱🇸", "answer": "ليسوتو" },
        { "question": "🇸🇿", "answer": "إسواتيني" },
        { "question": "🇲🇼", "answer": "مالاوي" },
        { "question": "🇳🇦", "answer": "ناميبيا" },
        { "question": "🇧🇼", "answer": "بوتسوانا" },
        { "question": "🇸🇷", "answer": "سورينام" },
        { "question": "🇬🇾", "answer": "غيانا" },
        { "question": "🇧🇿", "answer": "بليز" },
        { "question": "🇸🇴", "answer": "الصومال" },
        { "question": "🇬🇩", "answer": "غرينادا" },
        { "question": "🇱🇨", "answer": "سانت لوسيا" },
        { "question": "🇻🇨", "answer": "سانت فينسنت" },
        { "question": "🇦🇬", "answer": "أنتيغوا وباربودا" },
        { "question": "🇩🇲", "answer": "دومينيكا" },
        { "question": "🇰🇳", "answer": "سانت كيتس ونيفيس" },
        { "question": "🇦🇼", "answer": "أروبا" },
        { "question": "🇳🇷", "answer": "ناورو" },
        { "question": "🇵🇼", "answer": "بالاو" },
        { "question": "🇫🇲", "answer": "ميكرونيزيا" },
        { "question": "🇲🇭", "answer": "جزر مارشال" },
        { "question": "🇸🇧", "answer": "جزر سليمان" },
        { "question": "🇻🇺", "answer": "فانواتو" },
        { "question": "🇹🇴", "answer": "تونغا" },
        { "question": "🇼🇸", "answer": "ساموا" },
        { "question": "🇰🇮", "answer": "كيريباتي" },
        { "question": "🇹🇻", "answer": "توفالو" },
        { "question": "🇺🇿", "answer": "أوزباكستان" },
        { "question": "🇹🇱", "answer": "تيمور الشرقية" },
        { "question": "🇧🇹", "answer": "بوتان" },
        { "question": "🇲🇻", "answer": "جزر المالديف" },
        { "question": "🇸🇾", "answer": "سوريا" },
        { "question": "🇿🇲", "answer": "زامبيا" },
        { "question": "🇭🇰", "answer": "هونج كونج" },
        { "question": "🇲🇴", "answer": "ماكاو" },
        { "question": "🇦🇶", "answer": "أنتاركتيكا" },
        { "question": "🇧🇶", "answer": "الجزر الكاريبية الهولندية" },
        { "question": "🇨🇰", "answer": "جزر كوك" },
        { "question": "🇬🇮", "answer": "جبل طارق" },
        { "question": "🇮🇲", "answer": "جزيرة مان" },
        { "question": "🇯🇪", "answer": "جيرسي" },
        { "question": "🇬🇬", "answer": "غيرنزي" },
        { "question": "🇦🇩", "answer": "أندورا" },
        { "question": "🇱🇮", "answer": "ليختنشتاين" },
        { "question": "🇲🇨", "answer": "موناكو" },
        { "question": "🇻🇦", "answer": "الفاتيكان" },
        { "question": "🇬🇱", "answer": "غرينلاند" },
        { "question": "🇮🇴", "answer": "إقليم المحيط الهندي البريطاني" },
        { "question": "🇦🇨", "answer": "جزيرة أسينشن" },
        { "question": "🇸🇭", "answer": "سانت هيلينا" },
        { "question": "🇫🇰", "answer": "جزر فوكلاند" },
        { "question": "🇵🇫", "answer": "بولينيزيا الفرنسية" },
        { "question": "🇳🇨", "answer": "كاليدونيا الجديدة" },
        { "question": "🇾🇹", "answer": "مايوت" },
        { "question": "🇷🇪", "answer": "لا ريونيون" },
        { "question": "🇲🇶", "answer": "مارتينيك" },
        { "question": "🇬🇵", "answer": "غوادلوب" },
        { "question": "🇵🇲", "answer": "سانت بيير وميكلون" },
        { "question": "🇧🇱", "answer": "سانت بارثيليمي" },
        { "question": "🇲🇫", "answer": "سانت مارتن" },
        { "question": "🇬🇫", "answer": "غيانا الفرنسية" },
        { "question": "🇸🇽", "answer": "سانت مارتن الهولندية" },
        { "question": "🇨🇼", "answer": "كوراساو" },
        { "question": "🇦🇮", "answer": "أنغيلا" },
        { "question": "🇻🇬", "answer": "جزر العذراء البريطانية" },
        { "question": "🇻🇮", "answer": "جزر العذراء الأمريكية" },
        { "question": "🇲🇵", "answer": "جزر ماريانا الشمالية" },
        { "question": "🇬🇺", "answer": "غوام" },
        { "question": "🇦🇸", "answer": "ساموا الأمريكية" },
        { "question": "🇵🇳", "answer": "جزر بيتكيرن" },
        { "question": "🇳🇺", "answer": "نيوي" },
        { "question": "🇹🇰", "answer": "توكيلاو" },
        { "question": "🇨🇨", "answer": "جزر كوكوس" },
        { "question": "🇨🇽", "answer": "جزيرة الكريسماس" },
        { "question": "🇭🇲", "answer": "جزر هيرد وماكدونالد" },
        { "question": "🇳🇫", "answer": "جزيرة نورفولك" },
        { "question": "🇼🇫", "answer": "واليس وفوتونا" },
        { "question": "🇸🇯", "answer": "سفالبارد وجان ماين" },
        { "question": "🇦🇽", "answer": "جزر أولاند" },
        { "question": "🇧🇻", "answer": "جزيرة بوفيه" },
        { "question": "🇹🇫", "answer": "أراضي فرنسا الجنوبية" },
        { "question": "🇺🇲", "answer": "جزر الولايات المتحدة النائية" },
        { "question": "🇵🇭", "answer": "الفلبين" },
        { "question": "🇬🇸", "answer": "جورجيا الجنوبية" },
        { "question": "🇦🇶", "answer": "أنتاركتيكا" },
        { "question": "🇪🇦", "answer": "سيوتا وميليّة" },
        { "question": "🇮🇨", "answer": "جزر الكناري" },
        { "question": "🇩🇬", "answer": "دييغو غارسيا" },
        { "question": "🇹🇦", "answer": "تريستان دا كونا" },
        { "question": "🇲🇸", "answer": "مونتسيرات" },
        { "question": "🇰🇾", "answer": "جزر كايمان" },
        { "question": "🇹🇨", "answer": "جزر تركس وكايكوس" },
        { "question": "🇸🇸", "answer": "جنوب السودان" },
        { "question": "🇧🇧", "answer": "باربادوس" },
        { "question": "🇸🇷", "answer": "سورينام" },
        { "question": "🇬🇾", "answer": "غيانا" },
        { "question": "🇧🇿", "answer": "بليز" },
        { "question": "🇨🇷", "answer": "كوستاريكا" },
        { "question": "🇸🇻", "answer": "السلفادور" },
        { "question": "🇬🇹", "answer": "غواتيمالا" },
        { "question": "🇭🇳", "answer": "هندوراس" },
        { "question": "🇳🇮", "answer": "نيكاراغوا" },
        { "question": "🇵🇦", "answer": "بنما" },
        { "question": "🇩🇴", "answer": "جمهورية الدومينيكان" },
        { "question": "🇯🇲", "answer": "جامايكا" },
        { "question": "🇭🇹", "answer": "هايتي" },
        { "question": "🇹🇹", "answer": "ترينيداد وتوباغو" },
        { "question": "🇫🇯", "answer": "فيجي" },
        { "question": "🇵🇬", "answer": "بابوا غينيا الجديدة" },
        { "question": "🇬🇩", "answer": "غرينادا" },
        { "question": "🇱🇨", "answer": "سانت لوسيا" },
        { "question": "🇻🇨", "answer": "سانت فينسنت والغرينادين" },
        { "question": "🇦🇬", "answer": "أنتيغوا وباربودا" },
        { "question": "🇩🇲", "answer": "دومينيكا" },
        { "question": "🇰🇳", "answer": "سانت كيتس ونيفيس" },
        { "question": "🇱🇸", "answer": "ليسوتو" }
    ],

    // =============================================
    // 600 نقطة - صعب (أعلام نادرة أو متشابهة)
    // =============================================
    "600": [
        { "question": "🇨🇴 هذا العلم لأي بلد؟ (تشابه مع إكوادور)", "answer": "كولومبيا" },
        { "question": "🇪🇨 هذا العلم لأي بلد؟ (تشابه مع كولومبيا)", "answer": "الإكوادور" },
        { "question": "🇻🇪 هذا العلم لأي بلد؟", "answer": "فنزويلا" },
        { "question": "🇷🇴 هذا العلم لأي بلد؟ (تشابه مع تشاد)", "answer": "رومانيا" },
        { "question": "🇹🇩 هذا العلم لأي بلد؟ (تشابه مع رومانيا)", "answer": "تشاد" },
        { "question": "🇳🇿 هذا العلم لأي بلد؟", "answer": "نيوزيلندا" },
        { "question": "🇦🇺 هذا العلم لأي بلد؟", "answer": "أستراليا" },
        { "question": "🇸🇮 هذا العلم لأي بلد؟", "answer": "سلوفينيا" },
        { "question": "🇸🇰 هذا العلم لأي بلد؟", "answer": "سلوفاكيا" },
        { "question": "🇷🇸 هذا العلم لأي بلد؟", "answer": "صربيا" },
        { "question": "🇲🇪 هذا العلم لأي بلد؟", "answer": "الجبل الأسود" },
        { "question": "🇽🇰 هذا العلم لأي بلد؟", "answer": "كوسوفو" },
        { "question": "🇲🇰 هذا العلم لأي بلد؟", "answer": "مقدونيا الشمالية" },
        { "question": "🇦🇱 هذا العلم لأي بلد؟", "answer": "ألبانيا" },
        { "question": "🇧🇦 هذا العلم لأي بلد؟", "answer": "البوسنة والهرسك" },
        { "question": "🇭🇷 هذا العلم لأي بلد؟", "answer": "كرواتيا" },
        { "question": "🇲🇦 هذا العلم لأي بلد؟ (نجمة خضراء)", "answer": "المغرب" },
        { "question": "🇸🇳 هذا العلم لأي بلد؟", "answer": "السنغال" },
        { "question": "🇲🇱 هذا العلم لأي بلد؟", "answer": "مالي" },
        { "question": "🇬🇼 هذا العلم لأي بلد؟", "answer": "غينيا بيساو" },
        { "question": "🇬🇳 هذا العلم لأي بلد؟", "answer": "غينيا" },
        { "question": "🇸🇱 هذا العلم لأي بلد؟", "answer": "سيراليون" },
        { "question": "🇱🇷 هذا العلم لأي بلد؟ (يشبه العلم الأمريكي)", "answer": "ليبيريا" },
        { "question": "🇳🇷 هذا العلم لأي بلد؟", "answer": "ناورو" },
        { "question": "🇵🇼 هذا العلم لأي بلد؟", "answer": "بالاو" },
        { "question": "🇫🇲 هذا العلم لأي بلد؟", "answer": "ميكرونيزيا" },
        { "question": "🇲🇭 هذا العلم لأي بلد؟", "answer": "جزر مارشال" },
        { "question": "🇸🇧 هذا العلم لأي بلد؟", "answer": "جزر سليمان" },
        { "question": "🇻🇺 هذا العلم لأي بلد؟", "answer": "فانواتو" },
        { "question": "🇹🇴 هذا العلم لأي بلد؟", "answer": "تونغا" },
        { "question": "🇼🇸 هذا العلم لأي بلد؟", "answer": "ساموا" },
        { "question": "🇰🇮 هذا العلم لأي بلد؟", "answer": "كيريباتي" },
        { "question": "🇹🇻 هذا العلم لأي بلد؟", "answer": "توفالو" },
        { "question": "🇨🇻 هذا العلم لأي بلد؟", "answer": "الرأس الأخضر" },
        { "question": "🇸🇹 هذا العلم لأي بلد؟", "answer": "ساو تومي وبرينسيبي" },
        { "question": "🇬🇶 هذا العلم لأي بلد؟", "answer": "غينيا الاستوائية" },
        { "question": "🇧🇮 هذا العلم لأي بلد؟", "answer": "بوروندي" },
        { "question": "🇷🇼 هذا العلم لأي بلد؟", "answer": "رواندا" },
        { "question": "🇸🇿 هذا العلم لأي بلد؟", "answer": "إسواتيني" },
        { "question": "🇱🇸 هذا العلم لأي بلد؟", "answer": "ليسوتو" },
        { "question": "🇩🇯 هذا العلم لأي بلد؟", "answer": "جيبوتي" },
        { "question": "🇪🇷 هذا العلم لأي بلد؟", "answer": "إريتريا" },
        { "question": "🇧🇫 هذا العلم لأي بلد؟", "answer": "بوركينا فاسو" },
        { "question": "🇧🇯 هذا العلم لأي بلد؟", "answer": "بنين" },
        { "question": "🇹🇬 هذا العلم لأي بلد؟", "answer": "توغو" },
        { "question": "🇨🇫 هذا العلم لأي بلد؟", "answer": "جمهورية أفريقيا الوسطى" },
        { "question": "🇬🇦 هذا العلم لأي بلد؟", "answer": "الغابون" },
        { "question": "🇨🇬 هذا العلم لأي بلد؟", "answer": "الكونغو" },
        { "question": "🇦🇴 هذا العلم لأي بلد؟", "answer": "أنغولا" },
        { "question": "🇿🇼 هذا العلم لأي بلد؟", "answer": "زيمبابوي" },
        { "question": "🇳🇦 هذا العلم لأي بلد؟", "answer": "ناميبيا" },
        { "question": "🇧🇼 هذا العلم لأي بلد؟", "answer": "بوتسوانا" },
        { "question": "🇲🇬 هذا العلم لأي بلد؟", "answer": "مدغشقر" },
        { "question": "🇸🇨 هذا العلم لأي بلد؟", "answer": "سيشيل" },
        { "question": "🇲🇺 هذا العلم لأي بلد؟", "answer": "موريشيوس" },
        { "question": "🇰🇲 هذا العلم لأي بلد؟", "answer": "جزر القمر" },
        { "question": "🇲🇼 هذا العلم لأي بلد؟", "answer": "مالاوي" },
        { "question": "🇹🇱 هذا العلم لأي بلد؟", "answer": "تيمور الشرقية" },
        { "question": "🇧🇳 هذا العلم لأي بلد؟", "answer": "بروناي" },
        { "question": "🇧🇹 هذا العلم لأي بلد؟", "answer": "بوتان" },
        { "question": "🇲🇳 هذا العلم لأي بلد؟", "answer": "منغوليا" },
        { "question": "🇰🇬 هذا العلم لأي بلد؟", "answer": "قيرغيزستان" },
        { "question": "🇹🇲 هذا العلم لأي بلد؟", "answer": "تركمانستان" },
        { "question": "🇹🇯 هذا العلم لأي بلد؟", "answer": "طاجيكستان" },
        { "question": "🇱🇦 هذا العلم لأي بلد؟", "answer": "لاوس" },
        { "question": "🇰🇭 هذا العلم لأي بلد؟", "answer": "كمبوديا" },
        { "question": "🇲🇲 هذا العلم لأي بلد؟", "answer": "ميانمار" },
        { "question": "🇸🇷 هذا العلم لأي بلد؟", "answer": "سورينام" },
        { "question": "🇬🇾 هذا العلم لأي بلد؟", "answer": "غيانا" },
        { "question": "🇧🇿 هذا العلم لأي بلد؟", "answer": "بليز" },
        { "question": "🇵🇾 هذا العلم لأي بلد؟", "answer": "باراغواي" },
        { "question": "🇺🇾 هذا العلم لأي بلد؟", "answer": "الأوروغواي" },
        { "question": "🇧🇴 هذا العلم لأي بلد؟", "answer": "بوليفيا" },
        { "question": "🇵🇪 هذا العلم لأي بلد؟ (تشابه مع كندا)", "answer": "بيرو" },
        { "question": "🇬🇬 هذا العلم لأي بلد؟", "answer": "غيرنزي" },
        { "question": "🇯🇪 هذا العلم لأي بلد؟", "answer": "جيرسي" },
        { "question": "🇮🇲 هذا العلم لأي بلد؟", "answer": "جزيرة مان" },
        { "question": "🇬🇮 هذا العلم لأي بلد؟", "answer": "جبل طارق" },
        { "question": "🇦🇽 هذا العلم لأي بلد؟", "answer": "جزر أولاند" },
        { "question": "🇫🇴 هذا العلم لأي بلد؟", "answer": "جزر فارو" },
        { "question": "🇬🇱 هذا العلم لأي بلد؟", "answer": "غرينلاند" },
        { "question": "🇸🇯 هذا العلم لأي بلد؟", "answer": "سفالبارد وجان ماين" },
        { "question": "🇲🇸 هذا العلم لأي بلد؟", "answer": "مونتسيرات" },
        { "question": "🇦🇮 هذا العلم لأي بلد؟", "answer": "أنغيلا" },
        { "question": "🇰🇾 هذا العلم لأي بلد؟", "answer": "جزر كايمان" },
        { "question": "🇻🇬 هذا العلم لأي بلد؟", "answer": "جزر العذراء البريطانية" },
        { "question": "🇧🇶 هذا العلم لأي بلد؟", "answer": "الجزر الكاريبية الهولندية" },
        { "question": "🇸🇽 هذا العلم لأي بلد؟", "answer": "سانت مارتن" },
        { "question": "🇨🇼 هذا العلم لأي بلد؟", "answer": "كوراساو" },
        { "question": "🇦🇼 هذا العلم لأي بلد؟", "answer": "أروبا" },
        { "question": "🇵🇲 هذا العلم لأي بلد؟", "answer": "سانت بيير وميكلون" },
        { "question": "🇾🇹 هذا العلم لأي بلد؟", "answer": "مايوت" },
        { "question": "🇷🇪 هذا العلم لأي بلد؟", "answer": "لا ريونيون" },
        { "question": "🇲🇶 هذا العلم لأي بلد؟", "answer": "مارتينيك" },
        { "question": "🇬🇵 هذا العلم لأي بلد؟", "answer": "غوادلوب" },
        { "question": "🇵🇫 هذا العلم لأي بلد؟", "answer": "بولينيزيا الفرنسية" },
        { "question": "🇳🇨 هذا العلم لأي بلد؟", "answer": "كاليدونيا الجديدة" },
        { "question": "🇼🇫 هذا العلم لأي بلد؟", "answer": "واليس وفوتونا" },
        { "question": "🇹🇰 هذا العلم لأي بلد؟", "answer": "توكيلاو" },
        { "question": "🇳🇺 هذا العلم لأي بلد؟", "answer": "نيوي" },
        { "question": "🇨🇰 هذا العلم لأي بلد؟", "answer": "جزر كوك" },
        { "question": "🇵🇳 هذا العلم لأي بلد؟", "answer": "جزر بيتكيرن" },
        { "question": "🇦🇸 هذا العلم لأي بلد؟", "answer": "ساموا الأمريكية" },
        { "question": "🇬🇺 هذا العلم لأي بلد؟", "answer": "غوام" },
        { "question": "🇲🇵 هذا العلم لأي بلد؟", "answer": "جزر ماريانا الشمالية" },
        { "question": "🇻🇮 هذا العلم لأي بلد؟", "answer": "جزر العذراء الأمريكية" },
        { "question": "🇵🇷 هذا العلم لأي بلد؟", "answer": "بورتو ريكو" },
        { "question": "🇸🇲 هذا العلم لأي بلد؟", "answer": "سان مارينو" },
        { "question": "🇲🇨 هذا العلم لأي بلد؟ (تشابه مع إندونيسيا وبولندا)", "answer": "موناكو" },
        { "question": "🇻🇦 هذا العلم لأي بلد؟", "answer": "الفاتيكان" },
        { "question": "🇱🇮 هذا العلم لأي بلد؟", "answer": "ليختنشتاين" },
        { "question": "🇦🇩 هذا العلم لأي بلد؟", "answer": "أندورا" },
        { "question": "🇸🇸 هذا العلم لأي بلد؟", "answer": "جنوب السودان" },
        { "question": "🇬🇲 هذا العلم لأي بلد؟", "answer": "غامبيا" },
        { "question": "🇧🇧 هذا العلم لأي بلد؟", "answer": "باربادوس" },
        { "question": "🇹🇹 هذا العلم لأي بلد؟", "answer": "ترينيداد وتوباغو" },
        { "question": "🇩🇲 هذا العلم لأي بلد؟", "answer": "دومينيكا" },
        { "question": "🇰🇳 هذا العلم لأي بلد؟", "answer": "سانت كيتس ونيفيس" },
        { "question": "🇻🇨 هذا العلم لأي بلد؟", "answer": "سانت فينسنت والغرينادين" },
        { "question": "🇬🇩 هذا العلم لأي بلد؟", "answer": "غرينادا" },
        { "question": "🇱🇨 هذا العلم لأي بلد؟", "answer": "سانت لوسيا" },
        { "question": "🇧🇸 هذا العلم لأي بلد؟", "answer": "جزر البهاما" },
        { "question": "🇨🇺 هذا العلم لأي بلد؟", "answer": "كوبا" },
        { "question": "🇭🇹 هذا العلم لأي بلد؟", "answer": "هايتي" },
        { "question": "🇯🇲 هذا العلم لأي بلد؟", "answer": "جامايكا" },
        { "question": "🇱🇷 هذا العلم لأي بلد؟", "answer": "ليبيريا" },
        { "question": "🇸🇦 هذا العلم لأي بلد؟ (علم أخضر بخط وسيف)", "answer": "المملكة العربية السعودية" },
        { "question": "🇪🇬 هذا العلم لأي بلد؟ (نسر صلاح الدين)", "answer": "مصر" },
        { "question": "🇾🇪 هذا العلم لأي بلد؟ (ألوان بدون رمز)", "answer": "اليمن" },
        { "question": "🇸🇾 هذا العلم لأي بلد؟ (نجمتان خضراوان)", "answer": "سوريا" },
        { "question": "🇮🇶 هذا العلم لأي بلد؟ (الله أكبر)", "answer": "العراق" },
        { "question": "🇯🇴 هذا العلم لأي بلد؟ (نجمة بيضاء)", "answer": "الأردن" },
        { "question": "🇰🇼 هذا العلم لأي بلد؟ (مثلث أسود)", "answer": "الكويت" },
        { "question": "🇧🇭 هذا العلم لأي بلد؟ (خطوط متعرجة)", "answer": "البحرين" },
        { "question": "🇶🇦 هذا العلم لأي بلد؟ (لون كستنائي)", "answer": "قطر" },
        { "question": "🇴🇲 هذا العلم لأي بلد؟", "answer": "عُمان" }
    ]
};
