if (!window.gameQuestions) window.gameQuestions = {};

window.gameQuestions["رتب الحروف"] = {
    "__type__": "scramble",
    "200": [
        { "question": "", "answer": "تفاحة" }, { "question": "", "answer": "كتاب" }, { "question": "", "answer": "قلم" }, { "question": "", "answer": "نمر" }, { "question": "", "answer": "أسد" },
        { "question": "", "answer": "بحر" }, { "question": "", "answer": "سماء" }, { "question": "", "answer": "شمس" }, { "question": "", "answer": "نجمة" }, { "question": "", "answer": "خروف" },
        { "question": "", "answer": "قمر" }, { "question": "", "answer": "جبل" }, { "question": "", "answer": "نهر" }, { "question": "", "answer": "ورد" }, { "question": "", "answer": "موز" },
        { "question": "", "answer": "تمر" }, { "question": "", "answer": "تين" }, { "question": "", "answer": "عنب" }, { "question": "", "answer": "بلح" }, { "question": "", "answer": "شجر" },
        { "question": "", "answer": "ولد" }, { "question": "", "answer": "بنت" }, { "question": "", "answer": "باب" }, { "question": "", "answer": "بيت" }, { "question": "", "answer": "سور" },
        { "question": "", "answer": "قلب" }, { "question": "", "answer": "عين" }, { "question": "", "answer": "يد" }, { "question": "", "answer": "رجل" }, { "question": "", "answer": "أذن" },
        { "question": "", "answer": "أنف" }, { "question": "", "answer": "فم" }, { "question": "", "answer": "رأس" }, { "question": "", "answer": "قط" }, { "question": "", "answer": "كلب" },
        { "question": "", "answer": "فيل" }, { "question": "", "answer": "فأر" }, { "question": "", "answer": "نمل" }, { "question": "", "answer": "نحل" }, { "question": "", "answer": "صقر" },
        { "question": "", "answer": "خبز" }, { "question": "", "answer": "ملح" }, { "question": "", "answer": "ماء" }, { "question": "", "answer": "زيت" }, { "question": "", "answer": "سكر" },
        { "question": "", "answer": "بيض" }, { "question": "", "answer": "سمك" }, { "question": "", "answer": "لحم" }, { "question": "", "answer": "ثلج" }, { "question": "", "answer": "مطر" },
        { "question": "", "answer": "برق" }, { "question": "", "answer": "رعد" }, { "question": "", "answer": "ريح" }, { "question": "", "answer": "حقل" }, { "question": "", "answer": "علم" },
        { "question": "", "answer": "جيش" }, { "question": "", "answer": "وطن" }, { "question": "", "answer": "ملك" }, { "question": "", "answer": "شعب" }, { "question": "", "answer": "عدل" },
        { "question": "", "answer": "حب" }, { "question": "", "answer": "خير" }, { "question": "", "answer": "نور" }, { "question": "", "answer": "نار" }, { "question": "", "answer": "طين" },
        { "question": "", "answer": "فوز" }, { "question": "", "answer": "لعب" }, { "question": "", "answer": "نوم" }, { "question": "", "answer": "سيف" }, { "question": "", "answer": "درع" },
        { "question": "", "answer": "رمح" }, { "question": "", "answer": "قوس" }, { "question": "", "answer": "سهم" }, { "question": "", "answer": "كوب" }, { "question": "", "answer": "طبق" },
        { "question": "", "answer": "دلو" }, { "question": "", "answer": "فأس" }, { "question": "", "answer": "حبل" }, { "question": "", "answer": "خشب" }, { "question": "", "answer": "رمل" },
        { "question": "", "answer": "ذهب" }, { "question": "", "answer": "فضة" }, { "question": "", "answer": "حديد" }, { "question": "", "answer": "نحاس" }, { "question": "", "answer": "حجر" },
        { "question": "", "answer": "بئر" }, { "question": "", "answer": "جسر" }, { "question": "", "answer": "طرق" }, { "question": "", "answer": "ميل" }, { "question": "", "answer": "كيلو" },
        { "question": "", "answer": "صوت" }, { "question": "", "answer": "ضوء" }, { "question": "", "answer": "حلم" }, { "question": "", "answer": "عقل" }, { "question": "", "answer": "روح" },
        { "question": "", "answer": "ذكر" }, { "question": "", "answer": "فكر" }, { "question": "", "answer": "وقت" }, { "question": "", "answer": "يوم" }, { "question": "", "answer": "شهر" },
        { "question": "", "answer": "سنة" }, { "question": "", "answer": "قرن" }, { "question": "", "answer": "فجر" }, { "question": "", "answer": "ظهر" }, { "question": "", "answer": "عصر" },
        { "question": "", "answer": "ليل" }, { "question": "", "answer": "صبح" }, { "question": "", "answer": "مساء" }, { "question": "", "answer": "غد" }, { "question": "", "answer": "أمس" },
        { "question": "", "answer": "آن" }, { "question": "", "answer": "هنا" }, { "question": "", "answer": "هناك" }, { "question": "", "answer": "كيف" }, { "question": "", "answer": "لما" },
        { "question": "", "answer": "أين" }, { "question": "", "answer": "متى" }, { "question": "", "answer": "من" }, { "question": "", "answer": "هل" }, { "question": "", "answer": "كم" },
        { "question": "", "answer": "كل" }, { "question": "", "answer": "بعض" }, { "question": "", "answer": "غير" }, { "question": "", "answer": "دون" }, { "question": "", "answer": "بعد" },
        { "question": "", "answer": "قبل" }, { "question": "", "answer": "عند" }, { "question": "", "answer": "مع" }, { "question": "", "answer": "بين" }, { "question": "", "answer": "حول" },
        { "question": "", "answer": "فوق" }, { "question": "", "answer": "تحت" }, { "question": "", "answer": "خلف" }, { "question": "", "answer": "أمام" }, { "question": "", "answer": "يمن" },
        { "question": "", "answer": "يسر" }, { "question": "", "answer": "وسط" }, { "question": "", "answer": "طرف" }, { "question": "", "answer": "جزء" }, { "question": "", "answer": "نفس" },
        { "question": "", "answer": "ذات" }, { "question": "", "answer": "اسم" }, { "question": "", "answer": "فعل" }, { "question": "", "answer": "حرف" }, { "question": "", "answer": "جملة" },
        { "question": "", "answer": "نص" }, { "question": "", "answer": "شعر" }, { "question": "", "answer": "نثر" }, { "question": "", "answer": "كذب" }, { "question": "", "answer": "صدق" }
    ],
    "400": [
        { "question": "", "answer": "كمبيوتر" }, { "question": "", "answer": "مدرسة" }, { "question": "", "answer": "طائرة" }, { "question": "", "answer": "سيارة" }, { "question": "", "answer": "برتقال" },
        { "question": "", "answer": "بطيخة" }, { "question": "", "answer": "فراولة" }, { "question": "", "answer": "تمساح" }, { "question": "", "answer": "زرافة" }, { "question": "", "answer": "فندق" },
        { "question": "", "answer": "تليفون" }, { "question": "", "answer": "سفينة" }, { "question": "", "answer": "قطار" }, { "question": "", "answer": "دراجة" }, { "question": "", "answer": "جامعة" },
        { "question": "", "answer": "مكتبة" }, { "question": "", "answer": "مستشفى" }, { "question": "", "answer": "صيدلية" }, { "question": "", "answer": "عيادة" }, { "question": "", "answer": "مسجد" },
        { "question": "", "answer": "كنيسة" }, { "question": "", "answer": "شارع" }, { "question": "", "answer": "ميدان" }, { "question": "", "answer": "حديقة" }, { "question": "", "answer": "دولة" },
        { "question": "", "answer": "عاصمة" }, { "question": "", "answer": "قارة" }, { "question": "", "answer": "محيط" }, { "question": "", "answer": "بحيرة" }, { "question": "", "answer": "شلال" },
        { "question": "", "answer": "بركان" }, { "question": "", "answer": "زلزال" }, { "question": "", "answer": "إعصار" }, { "question": "", "answer": "فيضان" }, { "question": "", "answer": "عاصفة" },
        { "question": "", "answer": "سحابة" }, { "question": "", "answer": "مجرة" }, { "question": "", "answer": "صاروخ" }, { "question": "", "answer": "كائنات" }, { "question": "", "answer": "إنسان" },
        { "question": "", "answer": "حيوان" }, { "question": "", "answer": "نبات" }, { "question": "", "answer": "جماد" }, { "question": "", "answer": "معادن" }, { "question": "", "answer": "ألماس" },
        { "question": "", "answer": "مرجان" }, { "question": "", "answer": "كبريت" }, { "question": "", "answer": "ملابس" }, { "question": "", "answer": "فستان" }, { "question": "", "answer": "سروال" },
        { "question": "", "answer": "نظارة" }, { "question": "", "answer": "ساعة" }, { "question": "", "answer": "محفظة" }, { "question": "", "answer": "حقيبة" }, { "question": "", "answer": "دفتر" },
        { "question": "", "answer": "رصاص" }, { "question": "", "answer": "ممحاة" }, { "question": "", "answer": "مسطرة" }, { "question": "", "answer": "طابعة" }, { "question": "", "answer": "شاشة" },
        { "question": "", "answer": "مبرد" }, { "question": "", "answer": "غسالة" }, { "question": "", "answer": "خلاط" }, { "question": "", "answer": "مكواة" }, { "question": "", "answer": "مكنسة" },
        { "question": "", "answer": "خزانة" }, { "question": "", "answer": "طاولة" }, { "question": "", "answer": "كرسي" }, { "question": "", "answer": "أريكة" }, { "question": "", "answer": "شباك" },
        { "question": "", "answer": "ستارة" }, { "question": "", "answer": "سجادة" }, { "question": "", "answer": "صورة" }, { "question": "", "answer": "موسيقى" }, { "question": "", "answer": "فنان" },
        { "question": "", "answer": "ممثل" }, { "question": "", "answer": "مخرج" }, { "question": "", "answer": "كاتب" }, { "question": "", "answer": "شاعر" }, { "question": "", "answer": "مؤلف" },
        { "question": "", "answer": "رواية" }, { "question": "", "answer": "مجلة" }, { "question": "", "answer": "جريدة" }, { "question": "", "answer": "مذيع" }, { "question": "", "answer": "مبرمج" },
        { "question": "", "answer": "مصمم" }, { "question": "", "answer": "محلل" }, { "question": "", "answer": "باحث" }, { "question": "", "answer": "تلميذ" }, { "question": "", "answer": "طالب" },
        { "question": "", "answer": "أستاذ" }, { "question": "", "answer": "ممرض" }, { "question": "", "answer": "مسعف" }, { "question": "", "answer": "لاعب" }, { "question": "", "answer": "نجاح" },
        { "question": "", "answer": "تفوق" }, { "question": "", "answer": "صيام" }, { "question": "", "answer": "صلاة" }, { "question": "", "answer": "زكاة" }, { "question": "", "answer": "أمانة" },
        { "question": "", "answer": "إخلاص" }, { "question": "", "answer": "ذكرى" }, { "question": "", "answer": "سعاة" }, { "question": "", "answer": "حاسوب" }, { "question": "", "answer": "هاتف" },
        { "question": "", "answer": "شاحن" }, { "question": "", "answer": "قفل" }, { "question": "", "answer": "صندوق" }, { "question": "", "answer": "دهان" }, { "question": "", "answer": "مطبخ" },
        { "question": "", "answer": "ثلاجة" }, { "question": "", "answer": "طنجرة" }, { "question": "", "answer": "ملعقة" }, { "question": "", "answer": "إبريق" }, { "question": "", "answer": "قهوة" },
        { "question": "", "answer": "شاي" }, { "question": "", "answer": "عصير" }, { "question": "", "answer": "حلوى" }, { "question": "", "answer": "كعكة" }, { "question": "", "answer": "فرولة" },
        { "question": "", "answer": "تفاح" }, { "question": "", "answer": "كرز" }, { "question": "", "answer": "خوخ" }, { "question": "", "answer": "مشمش" }, { "question": "", "answer": "كمثرى" },
        { "question": "", "answer": "رمان" }, { "question": "", "answer": "ليمون" }, { "question": "", "answer": "ثوم" }, { "question": "", "answer": "بصل" }, { "question": "", "answer": "جزر" },
        { "question": "", "answer": "فلفل" }, { "question": "", "answer": "خيار" }, { "question": "", "answer": "بقدنس" }, { "question": "", "answer": "نعناع" }, { "question": "", "answer": "زعتر" },
        { "question": "", "answer": "فجل" }, { "question": "", "answer": "لفت" }, { "question": "", "answer": "ذرة" }, { "question": "", "answer": "قمح" }, { "question": "", "answer": "أرز" },
        { "question": "", "answer": "عدس" }, { "question": "", "answer": "فول" }, { "question": "", "answer": "حمص" }, { "question": "", "answer": "فستق" }, { "question": "", "answer": "بندق" },
        { "question": "", "answer": "جوز" }, { "question": "", "answer": "لوز" }, { "question": "", "answer": "هند" }, { "question": "", "answer": "صين" }, { "question": "", "answer": "يابان" }
    ],
    "600": [
        { "question": "", "answer": "مستشفى" }, { "question": "", "answer": "إمبراطور" }, { "question": "", "answer": "تكنولوجيا" }, { "question": "", "answer": "أخطبوط" }, { "question": "", "answer": "كهرباء" },
        { "question": "", "answer": "نيتروجين" }, { "question": "", "answer": "أوكسجين" }, { "question": "", "answer": "قسطنطينية" }, { "question": "", "answer": "ساندوتش" }, { "question": "", "answer": "إسكندرية" },
        { "question": "", "answer": "ديمقراطية" }, { "question": "", "answer": "فيزيائية" }, { "question": "", "answer": "رياضيات" }, { "question": "", "answer": "كيميائية" }, { "question": "", "answer": "بيولوجيا" },
        { "question": "", "answer": "إلكترونيات" }, { "question": "", "answer": "ميكانيكا" }, { "question": "", "answer": "برمجيات" }, { "question": "", "answer": "مستقبليات" }, { "question": "", "answer": "معلوماتية" },
        { "question": "", "answer": "إحصائيات" }, { "question": "", "answer": "استراتيجية" }, { "question": "", "answer": "اقتصادية" }, { "question": "", "answer": "تاريخية" }, { "question": "", "answer": "اجتماعية" },
        { "question": "", "answer": "ابتكارات" }, { "question": "", "answer": "اكتشافات" }, { "question": "", "answer": "محاضرات" }, { "question": "", "answer": "مناظرات" }, { "question": "", "answer": "مؤتمرات" },
        { "question": "", "answer": "إبداعات" }, { "question": "", "answer": "إنجازات" }, { "question": "", "answer": "طموحات" }, { "question": "", "answer": "تحديات" }, { "question": "", "answer": "نجاحات" },
        { "question": "", "answer": "مسابقات" }, { "question": "", "answer": "منافسات" }, { "question": "", "answer": "استثمارات" }, { "question": "", "answer": "تسويق" }, { "question": "", "answer": "دستورية" },
        { "question": "", "answer": "تشريعات" }, { "question": "", "answer": "إنسانية" }, { "question": "", "answer": "مسؤولية" }, { "question": "", "answer": "ازدهار" }, { "question": "", "answer": "استقرار" },
        { "question": "", "answer": "استدامة" }, { "question": "", "answer": "مسرحيات" }, { "question": "", "answer": "وثائقيات" }, { "question": "", "answer": "شفافية" }, { "question": "", "answer": "استنباط" },
        { "question": "", "answer": "استنتاج" }, { "question": "", "answer": "أرخبيل" }, { "question": "", "answer": "بيروقراطية" }, { "question": "", "answer": "ميتافيزيقا" }, { "question": "", "answer": "أنثروبولوجيا" },
        { "question": "", "answer": "سوسيولوجيا" }, { "question": "", "answer": "أيديولوجيا" }, { "question": "", "answer": "إمبريالية" }, { "question": "", "answer": "أوتوقراطية" }, { "question": "", "answer": "بروليتاريا" },
        { "question": "", "answer": "بروتوكول" }, { "question": "", "answer": "كاريكاتير" }, { "question": "", "answer": "سيناريو" }, { "question": "", "answer": "دبلوماسية" }, { "question": "", "answer": "ترانزيت" },
        { "question": "", "answer": "برلمان" }, { "question": "", "answer": "أكاديمية" }, { "question": "", "answer": "كاليفورنيا" }, { "question": "", "answer": "أستراليا" }, { "question": "", "answer": "إندونيسيا" },
        { "question": "", "answer": "موريتانيا" }, { "question": "", "answer": "بريطانيا" }, { "question": "", "answer": "البرازيل" }, { "question": "", "answer": "الأرجنتين" }, { "question": "", "answer": "المكسيك" },
        { "question": "", "answer": "كولومبيا" }, { "question": "", "answer": "باكستان" }, { "question": "", "answer": "أوزبكستان" }, { "question": "", "answer": "تركمانستان" }, { "question": "", "answer": "أذربيجان" },
        { "question": "", "answer": "إثيوبيا" }, { "question": "", "answer": "نيجيريا" }, { "question": "", "answer": "تنزانيا" }, { "question": "", "answer": "موزمبيق" }, { "question": "", "answer": "مدغشقر" },
        { "question": "", "answer": "نيوزيلندا" }, { "question": "", "answer": "هيمالايا" }, { "question": "", "answer": "إنترنت" }, { "question": "", "answer": "هيدروجين" }, { "question": "", "answer": "كربون" },
        { "question": "", "answer": "مغناطيس" }, { "question": "", "answer": "بلاتين" }, { "question": "", "answer": "يورانيوم" }, { "question": "", "answer": "ديناصور" }, { "question": "", "answer": "تلسكوب" },
        { "question": "", "answer": "ميكروسكوب" }, { "question": "", "answer": "بكتيريا" }, { "question": "", "answer": "فيروسات" }, { "question": "", "answer": "خلية" }, { "question": "", "answer": "بروتين" },
        { "question": "", "answer": "سيراميك" }, { "question": "", "answer": "محيطات" }, { "question": "", "answer": "قارات" }, { "question": "", "answer": "غابات" }, { "question": "", "answer": "صحراء" },
        { "question": "", "answer": "تضاريس" }, { "question": "", "answer": "خريطة" }, { "question": "", "answer": "بوصلة" }, { "question": "", "answer": "اتجاات" }, { "question": "", "answer": "ملاحة" },
        { "question": "", "answer": "طيران" }, { "question": "", "answer": "فضاء" }, { "question": "", "answer": "كواكب" }, { "question": "", "answer": "مجرات" }, { "question": "", "answer": "منظور" },
        { "question": "", "answer": "تصميم" }, { "question": "", "answer": "هندسة" }, { "question": "", "answer": "عمارة" }, { "question": "", "answer": "ديكور" }, { "question": "", "answer": "ألوان" },
        { "question": "", "answer": "إيقاع" }, { "question": "", "answer": "لحن" }, { "question": "", "answer": "أداء" }, { "question": "", "answer": "تعبير" }, { "question": "", "answer": "أسلوب" },
        { "question": "", "answer": "منطق" }, { "question": "", "answer": "فلسفة" }, { "question": "", "answer": "أخلاق" }, { "question": "", "answer": "قيم" }, { "question": "", "answer": "معايير" },
        { "question": "", "answer": "قواعد" }, { "question": "", "answer": "مبادئ" }, { "question": "", "answer": "نظم" }, { "question": "", "answer": "أسس" }, { "question": "", "answer": "بنية" },
        { "question": "", "answer": "تطور" }, { "question": "", "answer": "تحول" }, { "question": "", "answer": "تفاعل" }, { "question": "", "answer": "اتصال" }, { "question": "", "answer": "تبادل" },
        { "question": "", "answer": "مشاركة" }, { "question": "", "answer": "تواصل" }, { "question": "", "answer": "تفاهم" }, { "question": "", "answer": "انسجام" }, { "question": "", "answer": "توازن" },
        { "question": "", "answer": "استقرار" }, { "question": "", "answer": "نمو" }, { "question": "", "answer": "تقدم" }, { "question": "", "answer": "ازدهار" }, { "question": "", "answer": "نهضة" }
    ]
};
